database:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: ''
  database: 'wejh_nest'
  entities: ['/src/**/*.entity{.ts,.js}']
  #migrations: ['/database/migration/**/*{.ts,.js}']
  #migrationsTableName: 'migrations'
  #migrationsRun: true
  #cli:
    #migrationsDir: 'database/migration'
